#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration
bspc config border_radius        5
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config single_monocle       false
bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config automatic_scheme alternate

#BSPWM coloring

bspc config normal_border_color "#3c3836"
bspc config active_border_color "#504945"
bspc config focused_border_color "#98971a"
bspc config presel_feedback_color "#504945"

# Laptop monitor
bspc monitor DP-2 -d one two three four five six seven eight nine zero
# External monitor
# bspc monitor DP1 -d code web chat media other
# PC Monitor
# bspc monitor HDMI-1 -d code web chat media other

